src/main/resources/schemas/HL7V3/NE2008/multicacheschemas/PRPA_MT201306UV02.xsd
Changed the MinimumDegreeMatch value type to hl7 INT type.
=> FHAC-99: Changed the MinimumDegreeMatch value type to hl7 INT

pom.xml, src/main/resources/schemas/HL7V3/NE2008/multicacheschemas/PRPA_MT201306UV02.xsd
Changed the version, added changes related to 4.1.2
=> FHAC-114: Changed the version, added changes related to 4.1.2

src/main/resources/schemas/nhinc/common/PropertyAccess.xsd
First pull request to be merged for property POC for AdminGUI and Apache configurations migration.
=> Update for removing unused property refresh

pom.xml
1. Updated compiler source, targer values to 1.7
=> FHAC-463:Updated compiler source,target values to 1.7

src/main/resources/schemas/nhinc/common/AuditLog.xsd
Added EventTimestamp, EventID, EventType, EventOutcomeIndicator, RemoteHCID, RequestMessageId, RelatesTo, TransactionId, UserId and removed interface element from LogEventSecureRequestTypeand LogEventRequestType.
=> FHAC-626: xsd changes

src/main/resources/schemas/nhinc/common/AuditQueryLog.xsd
Fix issue found with namespace.
=> FHAC-690:Issue with elements namespace not binded to auditquerylog namespace

src/main/resources/schemas/nhinc/common/AuditQueryLog.xsd
@Chris and @alameluchidambaram
=> Changed the EventBeginDate and EventEndDate to be of type dateTime

pom.xml
Updated maven-jaxb2-plugin, plus other POM cleanup
=> FHAC-729: Updated maven-jaxb2-plugin

src/main/resources/schemas/nhinc/common/AuditLog.xsd, src/main/resources/schemas/nhinc/common/AuditQueryLog.xsd
Revert back EventOutComeIndicator field
@sailajaa @TabassumJafri, @christophermay07  Can you please review it?
=> FHAC-895: Revert EventOutComeIndicator field

src/main/resources/schemas/uddi/uddi_v3.xsd
Adding date time for last updated.
=> FHAC-1293 Added UDDI last updated attribute

pom.xml
=> Updated snapshot version to 5.0( This PR needs to merge before Webservices PR)

src/main/resources/schemas/nhinc/common/NhincCommon.xsd
Added optional conditions element to schema
=> FHAC-1530 added optional conditions element

pom.xml, src/main/resources/schemas/exchange/exchange.xsd, src/main/resources/schemas/exchange/organizationDirectory.xsd
schema to replace UDDIConnectionInfo.xml and to incorporate new FHIR HPD
=> CONN-1697 (previously Fhac 1532)

src/main/resources/schemas/exchange/organizationDirectory.xsd
Updates:
1. Added targetRegion, fullName, email and addressLine elements
2. Made phone in Contact a list.
3. Moved url and version in endpointType to endpointConfiguration element and made it a list.
=> Added targetRegion, fullname, addressLine,email to organizationdirectory schema

src/main/resources/schemas/exchange/exchange.xsd
adding isDisabled-default-false
=> CONN-1933 for both exchange and connect integration

src/main/resources/schemas/HL7V3/NE2008/multicacheschemas/XCPD_PLQ.xsd, src/main/resources/schemas/nhinc/common/NhincCommonAdapter.xsd, src/main/resources/schemas/nhinc/common/NhincCommonEntity.xsd
=> PLQ schema added, craeted new wrapper messages for PLQ

src/main/resources/schemas/nhinc/common/ExchangeManagement.xsd, src/main/resources/schemas/nhinc/common/NhincCommon.xsd, src/main/resources/schemas/nhinc/common/configAdmin.xsd
=> CONN-2016 exchange-management-operations-schema

src/main/resources/schemas/nhinc/common/ExchangeManagement.xsd
add validation-message to response-type
=> CONN-2206 complete-exchangemanagement

src/main/resources/schemas/nhinc/common/configAdmin.xsd
message required for the chain-of-trust
=> CONN-2269 view chain-of-trust

src/main/resources/schemas/nhinc/common/AdminGUIManagement.xsd
update xsd:date -- breaking jenkins
=> CONN-2192/2320 update xsd:date

src/main/resources/schemas/nhinc/common/LoadTestDataManagement.xsd
=> CONN-2238 loadtestdata

src/main/resources/schemas/exchange/exchange.xsd
Add SNI support into exchange type
=> CONN-2390-Add SNI element into exchange type

src/main/resources/schemas/nhinc/common/configAdmin.xsd
second part of the import wizard.
=> CONN-2437 import wizard part2

src/main/resources/schemas/nhinc/common/configAdmin.xsd
change referenceNumber to commonName
=> CONN-2442 import wizard improvement

src/main/resources/schemas/nhinc/common/configAdmin.xsd
resume point
new alias
soft-cancel
=> CONN-2446 improve wizard improvements

src/main/resources/schemas/nhinc/common/NhincCommonAdapter.xsd
adds new message types for Deferred Response Option Query
=> Conn 2454 - New Message types

src/main/resources/schemas/nhinc/common/NhincCommonAdapter.xsd
anta log(deferredResponseEndpoint)
=> CONN-2416 atna log
